// ============================================
// BRANDOPS SIMULATOR - Event Card Library
// ============================================
// Each card: { id, deck, title, storyText, effects, hasChoice, choiceA, choiceB, tags }
// Effects are stat deltas: positive = boost, negative = hit
// Stats: budget, demand, reputation, innovation, risk

const EVENT_CARDS = [

  // ════════════════════════════════════════
  // ECONOMIC DECK
  // ════════════════════════════════════════
  {
    id: "ec_01",
    deck: "economic",
    title: "Tariff Surge",
    storyText: "New import tariffs have increased your component costs by 30%. Your margins are shrinking fast.",
    effects: { budget: -15, demand: -5 },
    hasChoice: true,
    choiceA: { text: "Absorb the cost — protect customer pricing", effects: { budget: -10, reputation: +5 } },
    choiceB: { text: "Pass costs to consumer — raise prices",       effects: { budget: +5,  demand: -10, risk: +5 } },
    tags: ["supply_chain", "regulation"],
  },
  {
    id: "ec_02",
    deck: "economic",
    title: "Supply Chain Collapse",
    storyText: "A factory fire in your manufacturing country has halted production for two weeks.",
    effects: { budget: -10, demand: -15, risk: +10 },
    hasChoice: false,
    tags: ["supply_chain"],
  },
  {
    id: "ec_03",
    deck: "economic",
    title: "Labor Strike",
    storyText: "Workers at your overseas factory have walked out, demanding better wages. Production is at 30%.",
    effects: { budget: -8, demand: -10, reputation: -5, risk: +8 },
    hasChoice: true,
    choiceA: { text: "Negotiate — agree to wage increases",         effects: { budget: -12, reputation: +10, risk: -5 } },
    choiceB: { text: "Outsource to a different factory quickly",    effects: { budget: -5, innovation: -5, risk: +5 } },
    tags: ["supply_chain", "PR"],
  },
  {
    id: "ec_04",
    deck: "economic",
    title: "Inflation Wave",
    storyText: "Broad inflation is squeezing consumer spending. Discretionary purchases are down across your market.",
    effects: { demand: -10, budget: -5 },
    hasChoice: false,
    tags: ["market"],
  },
  {
    id: "ec_05",
    deck: "economic",
    title: "Interest Rate Cut",
    storyText: "The Federal Reserve cut rates. Consumer confidence is up and spending is rising.",
    effects: { demand: +12, budget: +5 },
    hasChoice: false,
    tags: ["market"],
  },
  {
    id: "ec_06",
    deck: "economic",
    title: "Investor Funding Round",
    storyText: "A venture capital firm has expressed interest in your brand. They want a pitch — fast.",
    effects: {},
    hasChoice: true,
    choiceA: { text: "Pitch aggressively — go for max funding",     effects: { budget: +25, risk: +10 } },
    choiceB: { text: "Play it safe — smaller ask, better terms",    effects: { budget: +12, reputation: +5 } },
    tags: ["investment"],
  },
  {
    id: "ec_07",
    deck: "economic",
    title: "Recession Fears",
    storyText: "Economic analysts are predicting a recession. Consumers are pulling back on premium purchases.",
    effects: { demand: -12, budget: -8, risk: +5 },
    hasChoice: false,
    tags: ["market"],
  },
  {
    id: "ec_08",
    deck: "economic",
    title: "Currency Fluctuation",
    storyText: "A strong dollar is making your exports more expensive overseas. International sales are slipping.",
    effects: { demand: -8, budget: -6 },
    hasChoice: false,
    tags: ["market", "supply_chain"],
  },
  {
    id: "ec_09",
    deck: "economic",
    title: "Black Friday Boom",
    storyText: "Holiday shopping season arrived early. Consumer spending is 20% above projections.",
    effects: { demand: +18, budget: +10 },
    hasChoice: false,
    tags: ["market"],
  },
  {
    id: "ec_10",
    deck: "economic",
    title: "Shipping Crisis",
    storyText: "A cargo ship blockage in a major shipping lane is delaying sea freight by 6 weeks.",
    effects: { budget: -10, demand: -8 },
    hasChoice: true,
    choiceA: { text: "Switch to air freight — expensive but fast",  effects: { budget: -15, demand: +5 } },
    choiceB: { text: "Wait it out — accept the delays",              effects: { demand: -10, reputation: -5 } },
    tags: ["supply_chain"],
  },
  {
    id: "ec_11",
    deck: "economic",
    title: "Government Grant",
    storyText: "Your brand qualifies for a small business innovation grant from the state government.",
    effects: { budget: +15, innovation: +5 },
    hasChoice: false,
    tags: ["regulation", "investment"],
  },
  {
    id: "ec_12",
    deck: "economic",
    title: "Raw Material Shortage",
    storyText: "A global shortage of a key material used in your product is driving costs up.",
    effects: { budget: -12, innovation: -5, risk: +5 },
    hasChoice: false,
    tags: ["supply_chain"],
  },
  {
    id: "ec_13",
    deck: "economic",
    title: "Trade Deal Signed",
    storyText: "A new trade agreement between the US and your country of origin slashes import costs.",
    effects: { budget: +12, demand: +5 },
    hasChoice: false,
    tags: ["regulation", "supply_chain"],
  },
  {
    id: "ec_14",
    deck: "economic",
    title: "Competitor Bankruptcy",
    storyText: "A major rival in your industry has filed for bankruptcy. Their market share is up for grabs.",
    effects: { demand: +15, reputation: +5 },
    hasChoice: false,
    tags: ["market"],
  },
  {
    id: "ec_15",
    deck: "economic",
    title: "Minimum Wage Hike",
    storyText: "New federal minimum wage legislation raises costs for your domestic retail partners.",
    effects: { budget: -8, risk: +5 },
    hasChoice: false,
    tags: ["regulation"],
  },

  // ════════════════════════════════════════
  // SOCIAL DECK
  // ════════════════════════════════════════
  {
    id: "so_01",
    deck: "social",
    title: "Influencer Scandal",
    storyText: "The influencer you partnered with was caught in a viral controversy. Your brand is being dragged into it.",
    effects: { reputation: -18, demand: -8, risk: +12 },
    hasChoice: true,
    choiceA: { text: "Cut ties publicly and fast",                  effects: { reputation: +8, budget: -5 } },
    choiceB: { text: "Stand by them — show loyalty",               effects: { reputation: -8, demand: +5 } },
    tags: ["PR", "social_media"],
  },
  {
    id: "so_02",
    deck: "social",
    title: "Viral Moment",
    storyText: "A customer posted a video using your product that got 10 million views overnight. You didn't plan this.",
    effects: { demand: +20, reputation: +10 },
    hasChoice: false,
    tags: ["social_media", "PR"],
  },
  {
    id: "so_03",
    deck: "social",
    title: "Environmental Boycott",
    storyText: "An environmental group has called for a boycott of your brand over your packaging practices.",
    effects: { reputation: -12, demand: -10, risk: +10 },
    hasChoice: true,
    choiceA: { text: "Launch an eco-rebrand initiative",            effects: { budget: -15, reputation: +15, risk: -8 } },
    choiceB: { text: "Dispute the claims with data",               effects: { risk: +5, reputation: -5 } },
    tags: ["PR", "regulation"],
  },
  {
    id: "so_04",
    deck: "social",
    title: "CEO Statement Backfire",
    storyText: "Your brand's CEO made a public statement on a political issue that divided your audience 50/50.",
    effects: { reputation: -10, demand: -5, risk: +8 },
    hasChoice: false,
    tags: ["PR"],
  },
  {
    id: "so_05",
    deck: "social",
    title: "Cultural Appropriation Allegation",
    storyText: "Critics claim your new campaign borrowed cultural elements without proper credit.",
    effects: { reputation: -15, risk: +12 },
    hasChoice: true,
    choiceA: { text: "Issue an apology and pull the campaign",      effects: { reputation: +5, budget: -8, demand: -5 } },
    choiceB: { text: "Defend the creative direction publicly",      effects: { reputation: -10, risk: +8 } },
    tags: ["PR", "social_media"],
  },
  {
    id: "so_06",
    deck: "social",
    title: "Celebrity Endorsement",
    storyText: "A major celebrity was spotted using your product and posted about it voluntarily. No contract needed.",
    effects: { demand: +18, reputation: +12 },
    hasChoice: false,
    tags: ["PR", "social_media"],
  },
  {
    id: "so_07",
    deck: "social",
    title: "Gen Z Trend Alignment",
    storyText: "A cultural trend that perfectly matches your brand identity is sweeping social media.",
    effects: { demand: +15, reputation: +8, innovation: +5 },
    hasChoice: false,
    tags: ["social_media", "trend"],
  },
  {
    id: "so_08",
    deck: "social",
    title: "Product Safety Rumor",
    storyText: "An unverified social media post claims your product caused an injury. The post is going viral.",
    effects: { reputation: -15, demand: -10, risk: +15 },
    hasChoice: true,
    choiceA: { text: "Get ahead of it — issue a transparent statement", effects: { reputation: +8, risk: -8 } },
    choiceB: { text: "Stay quiet and hope it blows over",            effects: { risk: +10, reputation: -5 } },
    tags: ["PR", "regulation"],
  },
  {
    id: "so_09",
    deck: "social",
    title: "Charity Partnership",
    storyText: "You partnered with a respected nonprofit for a cause marketing campaign.",
    effects: { reputation: +12, demand: +5, risk: -5 },
    hasChoice: false,
    tags: ["PR"],
  },
  {
    id: "so_10",
    deck: "social",
    title: "Meme-ification",
    storyText: "Your brand became an internet meme — the jokes are actually pretty funny and people seem to like you more.",
    effects: { demand: +12, reputation: +6 },
    hasChoice: false,
    tags: ["social_media", "trend"],
  },
  {
    id: "so_11",
    deck: "social",
    title: "Diversity Criticism",
    storyText: "A journalist published an article calling out your brand's lack of diversity in advertising.",
    effects: { reputation: -10, risk: +8 },
    hasChoice: true,
    choiceA: { text: "Launch an inclusive campaign immediately",     effects: { budget: -10, reputation: +12, risk: -5 } },
    choiceB: { text: "Release internal diversity statistics",        effects: { reputation: +5, risk: -3 } },
    tags: ["PR", "regulation"],
  },
  {
    id: "so_12",
    deck: "social",
    title: "Nostalgia Wave",
    storyText: "Retro and throwback aesthetics are trending. Consumers are craving brands that feel classic.",
    effects: { demand: +10, reputation: +5 },
    hasChoice: false,
    tags: ["trend"],
  },
  {
    id: "so_13",
    deck: "social",
    title: "Data Privacy Concern",
    storyText: "Consumer advocacy groups are pressuring brands to be more transparent about data collection.",
    effects: { risk: +10, reputation: -8 },
    hasChoice: true,
    choiceA: { text: "Publish a clear data transparency report",     effects: { reputation: +10, risk: -8, budget: -5 } },
    choiceB: { text: "Update terms quietly — hope no one notices",  effects: { risk: +5 } },
    tags: ["regulation", "PR"],
  },
  {
    id: "so_14",
    deck: "social",
    title: "Sports Sponsorship Win",
    storyText: "Your brand was featured prominently during a major sporting event broadcast.",
    effects: { demand: +15, reputation: +10, budget: -12 },
    hasChoice: false,
    tags: ["PR"],
  },
  {
    id: "so_15",
    deck: "social",
    title: "Fake Review Scandal",
    storyText: "Investigative journalists revealed that several positive reviews of your product were fabricated.",
    effects: { reputation: -20, risk: +15, demand: -10 },
    hasChoice: false,
    tags: ["PR", "regulation"],
  },

  // ════════════════════════════════════════
  // INNOVATION DECK
  // ════════════════════════════════════════
  {
    id: "in_01",
    deck: "innovation",
    title: "Competitor Tech Leap",
    storyText: "Your main rival just announced a product with features 2 years ahead of yours. Tech press is gushing.",
    effects: { demand: -12, innovation: -10, reputation: -5 },
    hasChoice: true,
    choiceA: { text: "Rush an R&D sprint — fast follow strategy",   effects: { budget: -15, innovation: +12 } },
    choiceB: { text: "Compete on price and reliability instead",    effects: { demand: +5, budget: -5 } },
    tags: ["trend", "competition"],
  },
  {
    id: "in_02",
    deck: "innovation",
    title: "AI Integration Opportunity",
    storyText: "A new AI platform could be integrated into your product pipeline, automating part of your process.",
    effects: {},
    hasChoice: true,
    choiceA: { text: "Full integration — go all in on AI",          effects: { budget: -20, innovation: +20, risk: +5 } },
    choiceB: { text: "Pilot test only — limited rollout",           effects: { budget: -8, innovation: +8 } },
    tags: ["trend", "innovation"],
  },
  {
    id: "in_03",
    deck: "innovation",
    title: "Patent Infringement Claim",
    storyText: "A tech firm claims your newest product feature violates their patent. Legal costs incoming.",
    effects: { budget: -15, risk: +15, innovation: -5 },
    hasChoice: false,
    tags: ["regulation", "competition"],
  },
  {
    id: "in_04",
    deck: "innovation",
    title: "R&D Breakthrough",
    storyText: "Your team made an unexpected discovery that could significantly improve your core product.",
    effects: { innovation: +18, reputation: +8 },
    hasChoice: false,
    tags: ["innovation"],
  },
  {
    id: "in_05",
    deck: "innovation",
    title: "App Goes Down",
    storyText: "Your brand's app or digital platform crashed for 6 hours. Customers are furious.",
    effects: { reputation: -12, demand: -8, risk: +8 },
    hasChoice: false,
    tags: ["innovation", "PR"],
  },
  {
    id: "in_06",
    deck: "innovation",
    title: "Sustainability Tech",
    storyText: "New eco-manufacturing technology is available that reduces your carbon footprint significantly.",
    effects: {},
    hasChoice: true,
    choiceA: { text: "Adopt it fully — lead the green wave",        effects: { budget: -18, reputation: +15, risk: -8, innovation: +8 } },
    choiceB: { text: "Ignore it — not in your budget right now",    effects: { risk: +5, reputation: -3 } },
    tags: ["innovation", "regulation"],
  },
  {
    id: "in_07",
    deck: "innovation",
    title: "Product Recall",
    storyText: "A defect was found in your latest product batch. A voluntary recall is strongly recommended.",
    effects: { budget: -20, reputation: -15, demand: -12, risk: +18 },
    hasChoice: true,
    choiceA: { text: "Announce recall proactively",                 effects: { reputation: +10, risk: -10 } },
    choiceB: { text: "Quietly fix it and hope no one noticed",      effects: { risk: +15 } },
    tags: ["regulation", "PR"],
  },
  {
    id: "in_08",
    deck: "innovation",
    title: "Copycat Product",
    storyText: "A budget brand has released an almost identical product at half the price.",
    effects: { demand: -10, budget: -5, innovation: -5 },
    hasChoice: true,
    choiceA: { text: "Double down on quality and premium positioning", effects: { reputation: +8, innovation: +5 } },
    choiceB: { text: "Match their price point",                      effects: { demand: +8, budget: -10 } },
    tags: ["competition"],
  },
  {
    id: "in_09",
    deck: "innovation",
    title: "Tech Partnership",
    storyText: "A leading tech company wants to co-develop a new version of your product.",
    effects: { innovation: +15, reputation: +10, budget: -8 },
    hasChoice: false,
    tags: ["innovation"],
  },
  {
    id: "in_10",
    deck: "innovation",
    title: "Data Breach",
    storyText: "Hackers accessed customer data in your system. 50,000 records were exposed.",
    effects: { reputation: -20, risk: +20, budget: -15 },
    hasChoice: false,
    tags: ["regulation", "PR"],
  },
  {
    id: "in_11",
    deck: "innovation",
    title: "Award Recognition",
    storyText: "Your product won a major industry innovation award, covered by trade press and mainstream media.",
    effects: { reputation: +12, innovation: +8, demand: +8 },
    hasChoice: false,
    tags: ["innovation", "PR"],
  },
  {
    id: "in_12",
    deck: "innovation",
    title: "Social Commerce Integration",
    storyText: "A major social platform launched a native shopping feature perfect for your product category.",
    effects: { demand: +12, innovation: +5 },
    hasChoice: true,
    choiceA: { text: "Be an early adopter — go all in",             effects: { budget: -8, demand: +10, innovation: +5 } },
    choiceB: { text: "Wait and see how it performs",                effects: {} },
    tags: ["trend", "innovation"],
  },
  {
    id: "in_13",
    deck: "innovation",
    title: "Automation Backlash",
    storyText: "After announcing automated production upgrades, consumer groups accused you of eliminating jobs.",
    effects: { reputation: -8, risk: +8 },
    hasChoice: false,
    tags: ["PR", "regulation"],
  },
  {
    id: "in_14",
    deck: "innovation",
    title: "UX Redesign Bomb",
    storyText: "Your app's major redesign launched to overwhelmingly negative reviews. Users hate the new interface.",
    effects: { reputation: -12, demand: -10, innovation: -5 },
    hasChoice: false,
    tags: ["innovation", "PR"],
  },
  {
    id: "in_15",
    deck: "innovation",
    title: "Beta Launch Success",
    storyText: "Your beta program attracted tech-forward early adopters who are becoming passionate brand advocates.",
    effects: { demand: +10, innovation: +10, reputation: +8 },
    hasChoice: false,
    tags: ["innovation", "trend"],
  },

  // ════════════════════════════════════════
  // WILDCARD DECK
  // ════════════════════════════════════════
  {
    id: "wc_01",
    deck: "wildcard",
    title: "Natural Disaster",
    storyText: "A hurricane destroyed a key distribution hub. Three regions can't receive your product for 30 days.",
    effects: { budget: -20, demand: -15, reputation: -5, risk: +10 },
    hasChoice: false,
    tags: ["supply_chain"],
  },
  {
    id: "wc_02",
    deck: "wildcard",
    title: "Presidential Mention",
    storyText: "The President mentioned your brand positively in a speech. Half the country now loves you. Half doesn't.",
    effects: { demand: +10, reputation: -5, risk: +8 },
    hasChoice: false,
    tags: ["PR"],
  },
  {
    id: "wc_03",
    deck: "wildcard",
    title: "Global Pandemic Scare",
    storyText: "A new health scare is keeping consumers home. E-commerce explodes. Physical retail collapses.",
    effects: { demand: -8, innovation: +10, budget: +5 },
    hasChoice: true,
    choiceA: { text: "Pivot to direct-to-consumer digital model",   effects: { innovation: +10, demand: +12, budget: -15 } },
    choiceB: { text: "Wait for things to normalize",               effects: { demand: -8 } },
    tags: ["market", "trend"],
  },
  {
    id: "wc_04",
    deck: "wildcard",
    title: "Alien Contact (Simulation Event)",
    storyText: "Scientists announced what might be first contact with extraterrestrial intelligence. Every brand on Earth is trying to react. The market is insane.",
    effects: { demand: +20, innovation: +15, risk: +15 },
    hasChoice: false,
    tags: ["wildcard"],
  },
  {
    id: "wc_05",
    deck: "wildcard",
    title: "Brand Collab Offer",
    storyText: "An iconic brand from a completely different industry wants to co-release a limited edition product with you.",
    effects: {},
    hasChoice: true,
    choiceA: { text: "Accept — this is your moment to go viral",   effects: { budget: -10, demand: +20, reputation: +12 } },
    choiceB: { text: "Decline — protect brand identity",           effects: { innovation: +5, reputation: +3 } },
    tags: ["trend", "PR"],
  },
  {
    id: "wc_06",
    deck: "wildcard",
    title: "Congressional Hearing",
    storyText: "Your industry is called to testify before Congress over consumer protection concerns.",
    effects: { risk: +15, reputation: -10, budget: -10 },
    hasChoice: true,
    choiceA: { text: "Send the CEO — own the narrative",           effects: { reputation: +8, risk: -5 } },
    choiceB: { text: "Send lawyers — minimize exposure",           effects: { budget: -10, risk: -3 } },
    tags: ["regulation", "PR"],
  },
  {
    id: "wc_07",
    deck: "wildcard",
    title: "Time Magazine Feature",
    storyText: "Time Magazine called your brand 'one of the most innovative companies of the year.'",
    effects: { reputation: +20, demand: +12, innovation: +8 },
    hasChoice: false,
    tags: ["PR"],
  },
  {
    id: "wc_08",
    deck: "wildcard",
    title: "Class Action Lawsuit",
    storyText: "A group of consumers has filed a class action lawsuit over a product claim in your advertising.",
    effects: { budget: -25, risk: +20, reputation: -15 },
    hasChoice: false,
    tags: ["regulation", "PR"],
  },
  {
    id: "wc_09",
    deck: "wildcard",
    title: "Super Bowl Spot Opens Up",
    storyText: "A brand just dropped their Super Bowl ad slot last minute. You can buy it at a premium.",
    effects: {},
    hasChoice: true,
    choiceA: { text: "Buy the slot — go for broke",                effects: { budget: -30, demand: +25, reputation: +15 } },
    choiceB: { text: "Pass — you'll spend smarter elsewhere",      effects: {} },
    tags: ["PR", "market"],
  },
  {
    id: "wc_10",
    deck: "wildcard",
    title: "Hostile Takeover Attempt",
    storyText: "A larger corporation is attempting to acquire your brand. Investors are excited. The team is nervous.",
    effects: { budget: +20, risk: +15, reputation: -5 },
    hasChoice: true,
    choiceA: { text: "Fight it — stay independent",               effects: { budget: -15, reputation: +10, risk: +5 } },
    choiceB: { text: "Negotiate terms — protect the brand identity", effects: { budget: +15, innovation: +5 } },
    tags: ["market", "investment"],
  },
  {
    id: "wc_11",
    deck: "wildcard",
    title: "Documentary Exposé",
    storyText: "A Netflix documentary is being made about practices in your industry. You're mentioned prominently.",
    effects: { risk: +12, reputation: -10 },
    hasChoice: true,
    choiceA: { text: "Cooperate with filmmakers — control your narrative", effects: { reputation: +8, risk: -5 } },
    choiceB: { text: "Decline all access",                         effects: { risk: +8, reputation: -8 } },
    tags: ["PR"],
  },
  {
    id: "wc_12",
    deck: "wildcard",
    title: "Olympics Sponsorship",
    storyText: "You're offered an official sponsorship package for the upcoming Olympic Games.",
    effects: {},
    hasChoice: true,
    choiceA: { text: "Full sponsorship — huge exposure",           effects: { budget: -25, demand: +20, reputation: +15 } },
    choiceB: { text: "Grassroots athlete deals only",              effects: { budget: -10, reputation: +8, demand: +8 } },
    tags: ["PR", "market"],
  },
];

// Helper to get cards by deck
const CardLibrary = {
  getByDeck(deckName) {
    return EVENT_CARDS.filter(c => c.deck === deckName);
  },
  getRandom(deckName) {
    const deck = this.getByDeck(deckName);
    return deck[Math.floor(Math.random() * deck.length)];
  },
  getById(id) {
    return EVENT_CARDS.find(c => c.id === id);
  },
  getAllDecks() {
    return ["economic", "social", "innovation", "wildcard"];
  },
  // Returns all cards that affect sentiment (for teacher reference)
  getSentimentCards() {
    return EVENT_CARDS.filter(c =>
      c.effects?.sentiment ||
      c.choiceA?.effects?.sentiment ||
      c.choiceB?.effects?.sentiment
    );
  }
};
